# # set
# - ref: https://wiki.archlinux.org/title/tmux
set-option -g focus-events on # autoread
set-option -g repeat-time 0 # tmux command wihtout delay time
set-option -s escape-time 50 # can't be 0

# # terminfo config
set-option -g default-terminal 'tmux-256color'
# - ref: https://www.mail-archive.com/debian-user@lists.debian.org/msg757834.html
# - ref: https://cloud.tencent.com/developer/ask/sof/874641
# - ref: https://github.com/tmux/tmux/wiki/FAQ
# - fixed tmux color
# - fixed ANSI escape code Ex: 0;10;1c
set-option -sa terminal-overrides ",*256color:Tc:smcup@:rmcup@"

# # status bar
wg_date=" %m-%d-%Y"
wg_time=" %H:%M"
wg_session="[#S] "
set -g status-position bottom
set -g status-right "#[bg=black]${wg_time}"
set -g status-left "#[bg=black]${wg_session}"
set -g status-style "bg=black"
set -g message-style "bg=yellow, fg=black"
set -g window-status-current-style "bg=yellow,fg=black"
set -g window-status-style "bg=black"
set -g renumber-windows on # renumber all windows when any window is closed
set -g status-left-length 50
set -g base-index 1 # Window indexing begins at 1 (not 0)
set -g pane-base-index 1 # pane indexing begins at 1 as well

# # vi key
set -g mode-keys vi

# # keybind
# - ref: https://github.com/timotheecour/dinocode/blob/master/tmux_list_keys_escaped.txt
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind -r p paste-buffer
bind -r r source-file ~/.config/tmux/tmux.conf; run-shell "echo ----Reload tmux.conf----"; run-shell "tmux showenv -s"
bind -r f run-shell "tmux neww -n tmux-sessionizer tmux-sessionizer"
bind -r e run-shell "tmux neww -n tmux-session-selector tmux-session-selector"
bind -r c neww
bind -r x confirm-before kill-window
bind -r h select-window -t 1
bind -r j select-window -t 2
bind -r k select-window -t 3
bind -r l select-window -t 4
bind -r \; select-window -t 5

# # clipboard
# - ref: https://github.com/tmux/tmux/wiki/Clipboard
# - If on: can interact with X11 clipboard and OSC52 auto wihtout yank script
set -s set-clipboard on
# - ref: https://www.linuxquestions.org/questions/slackware-14/tmux-copy-paste-clipboard-4175710195-print/
# - ref: https://sunaku.github.io/tmux-yank-osc52.html
# - note: OSC 52 is one direction from remote to local
# - note: X11 forwarding, The disadvantage of this X11 forwarding solution is that you need
#   to run SSH with the -X or -Y options while also keeping environment variables like
#   $DISPLAY and $XAUTHORITY up to date as you disconnect and reconnect your remote sessions.
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe 'yank > #{pane_tty}'\; display-message "Yank";
