# https://wiki.archlinux.org/title/tmux
set-option -g focus-events on # autoread
set-option -g repeat-time 0 # tmux command wihtout delay time
set -s escape-time 50 # can't be 0

# terminfo config
set-option -g default-terminal 'tmux-256color'
set-option -ga terminal-overrides ",*256col*:Tc"

# status bar
wg_date=" %m-%d-%Y"
wg_time=" %H:%M"
wg_prefix="#{?client_prefix,-- PREFIX --,}"
wg_session="[#S] "
set -g status-position bottom
set -g status-right "#[bg=#000000, fg=#cdd6f4]${wg_time}"
set -g status-left  "#[bg=#000000, fg=#cdd6f4]${wg_session}"
set -g status-style   "bg=#000000, fg=#cdd6f4"
set -g message-style  "bg=#dfff00, fg=#000000,bold"
set-window-option -g window-status-current-style "bg=#dfff00,fg=#000000,bold"
set-window-option -g window-status-style "bg=#000000, fg=#cdd6f4"
set -g renumber-windows on # renumber all windows when any window is closed
set -g status-left-length 50
set -g base-index 1 # Window indexing begins at 1 (not 0)
set-window-option -g pane-base-index 1 # pane indexing begins at 1 as well


# keybind
# https://github.com/timotheecour/dinocode/blob/master/tmux_list_keys_escaped.txt
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind -r p paste-buffer
bind -r r source-file ~/.config/tmux/tmux.conf \;
    run-shell "eval $(tmux showenv -s | grep -E '^(SSH|DISPLAY)')";
    run-shell "echo ----Reload tmux.conf----"
    run-shell "tmux showenv -s"
bind -r f run-shell "tmux neww -n tmux-sessionizer tmux-sessionizer"
bind -r e run-shell "tmux neww -n tmux-session-selector tmux-session-selector"
bind -r c neww
bind -r x confirm-before kill-window
bind -r h select-window -t 1
bind -r j select-window -t 2
bind -r k select-window -t 3
bind -r l select-window -t 4
bind -r \; select-window -t 5

# vi mode
set-window-option -g mode-keys vi

# clipboard
# https://github.com/tmux/tmux/wiki/Clipboard
# https://www.linuxquestions.org/questions/slackware-14/tmux-copy-paste-clipboard-4175710195-print/
set -s set-clipboard off # If the copy-pipe method is used with a terminal that also supports set-clipboard, the two can conflict. It is best to disable set-clipboard in that case:
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xsel -i -b"\; display-message "Copy to clipbaord"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel"\; display-message "Copy to clipbaord"
