#!/bin/bash

if ! git rev-parse --is-inside-work-tree &>/dev/null; then
    exit 1
fi

git -C "$(git rev-parse --show-toplevel)" ls-files --full-name --cached --exclude-standard \
  | awk -v root="$(git rev-parse --show-toplevel)" '{ print root "/" $0 }' \
  | fzf --multi
