#!/usr/bin/env bash

if [ -z "$1" ]; then
    target=$(git branch --show-current)
else
    target=$1
fi

if ! git show-ref --verify --quiet "refs/heads/$target"; then
    echo "Warning: not exist '$target'"
    exit 1
fi

for branch in $(git branch --format='%(refname:short)'); do
    if [ "$branch" != "$target" ]; then
        base=$(git merge-base "$target" "$branch")
        count=$(git rev-list --count "$base..$target")

        if [ "$count" -gt 0 ]; then
            echo "$count commits from $branch (base: ${base:0:7})"
        fi
    fi
done | sort -n
