#!/usr/bin/env bash
set -euo pipefail
# https://github.com/omerxx/tmux-sessionx/tree/main
# https://www.youtube.com/watch?v=GH3kpsbbERo

tmux="tmux -u" # imperative

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items+=$(printf "%s\n\b" "${HOME}")
    items+=$(find /NOBACKUP/$HOSTNAME/jasonli/*project* -mindepth 1 -maxdepth 1 -type d 2>/dev/null) || true
    #while IFS= read -r line; do
    #    items+=("$line")
    #done < <(find /NOBACKUP/"$HOSTNAME"/jasonli/*project* -mindepth 1 -maxdepth 1 -type d 2>/dev/null || true)
    selected=$(printf "%s" "${items[@]}" | fzf) || true
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# check if the tmux session exists, nothing is echoed in when there are no sessions, otherwise the list is reported.
if ! ${tmux} has-session -t=$selected_name 2> /dev/null; then
    # create the tmux session
    ${tmux} new-session -ds $selected_name -c $selected
fi

if [[ -z "${TMUX-}" ]]; then
    # if not in tmux
    ${tmux} attach -t $selected_name
else
    # if in tmux
    ${tmux} switch-client -t $selected_name
fi
