#!/usr/bin/bash
tmux="tmux -u" # imperative

if [[ $# -eq 1 ]]; then
    selected=$2
else
    selected=$(find ~ -mindepth 1 -maxdepth 1 -type d | fzf)
    #selected=$(find /NOBACKUP/$HOSTNAME/jasonli -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# check if the tmux session exists
if ! ${tmux} has-session -t=$selected_name 2> /dev/null; then
    # create the tmux session
    ${tmux} new-session -ds $selected_name -c $selected
fi

if [[ "${TMUX-}" != '' ]];
    # if not in tmux
    ${tmux} attach -t $selected_name
then
    # if in tmux
    ${tmux} switch-client -t $selected_name
fi
