#!/usr/bin/env bash

tmux="tmux -u"

selected=$(tmux list-sessions)
if [[ -z ${selected} ]]; then
    exec 'tmux-sessionizer'
    exit 0
fi

selected=$(tmux list-sessions -F '#{?session_attached,,#{session_name}}')
if [[ -z $selected ]]; then
    exit 0
fi

selected=$(tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
    sed '/^$/d' |\
    fzf
)
if [[ -z $selected ]]; then
    exit 0
fi

selected_name=${selected}

if [[ -z "${TMUX}" ]]; then
    # if not in tmux
    ${tmux} attach -t $selected_name
else
    # if in tmux
    ${tmux} switch-client -t $selected_name
fi
