#!/usr/bin/env bash

tmux="tmux -u"

if [[ -z $(${tmux} ls 2> /dev/null) ]]; then
    selected="$(pwd)"
    selected_name=$(basename "${selected}")
    ${tmux} new-session -ds $selected_name -c $selected
    ${tmux} attach -t $selected_name
    exit 0
fi

if [[ -z "${TMUX}" ]]; then
    # if not in tmux
    selected=$(${tmux} list-sessions |\
        sed "s/:.*//g" |\
        sed "/^$/d" |\
        fzf
    )
else
    # if in tmux
    current_session=$(${tmux} display-message -p '#S')

    selected=$(${tmux} list-sessions |\
        sed "s/:.*//g" |\
        sed "/\<${current_session}\>/d" |\
        sed "/^$/d" |\
        fzf
    )
fi

#selected=$(tmux list-sessions -F '#{?session_attached,,#{session_name}}' |\
#    sed '/^$/d' |\
#    fzf
#)

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=${selected}

if [[ -z "${TMUX}" ]]; then
    # if not in tmux
    ${tmux} attach -t $selected_name
else
    # if in tmux
    ${tmux} switch-client -t $selected_name
fi
